### PR TITLE
Feature/OE-5521

### PR DESCRIPTION
**Pull request by vetusko**
Common drugs administration page

### CODE REVIEW

**Comment by himanshupatel79** [comment]
## CODE REVIEW COMMENTS

A) AdminController.php
Remove actionIndex Method, as it not in used anywhere and don’t have any definition.
Third parameter in Comment block of actionCommonDrugsAdd function is wrong. line 94

B) commondrugsadmin.js
should have generalised name like admin.js , so we can use to add and maintain same file all admin functions in future.
Header Comment Blocks need to be added, same as other files

**Comment by vetusko** [comment]
A) OK

B) As this module use the ElementType model and inside the ElementType the name of this module render page is Details, that's why this file named like this (you can see the same naming convention inside the view directory). I don't think it should be renamed. This is a little bit weird solution inside the modules... They used element types and event-like "commands" to build the modules functionality (just like create, update, view, etc). I think renaming this will cause inconsistency with other modules model names as well. 

C) There are two ways to handle JS files: 1. create a big file for each module admin page with all the functions in it, and include the whole file every time when an admin page will load (this can be done by renaming this to simply admin.js, and put all the admin JS functions inside it), OR 2. write smaller JS files with functions specified for the selected admin page only, and always include only these smaller files, because it is not necessary to load the functions for the other admin pages. There should be common functions, and they can be placed in an admin.js, but I think menu specific JS functions can live in smaller files.

**Comment by petergallagher** [comment]
I would personally rather see lots of small, specific JS files which can be included when required rather than one large unwieldy file full of everything for the admin system. If it gets to the point where the multiple requests are an issue we can concat the files before serving them.

**Comment by vetusko** [comment]
Changes commited and pushed:
- Removed actionIndex method from the controller (A)
- HTML tags are lower case now and /a added

**Comment by vetusko** [comment]
Sorry, fixed... Actually I also fixed it on 5518, because I merged them together locally... :)

**Pull request merged**
